server:
  port: 8001

spring:
  devtools:
    restart:
      # 开启热部署（更改文件后，自动重启）
      enabled: true
      additional-paths: src/main/java
  application:
    name: cloud-provider-hystrix-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://sh-cynosdbmysql-grp-cf0bewmq.sql.tencentcdb.com:21078/SpringCloudDemo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: baiyun666@
    #    driver-class-name: com.mysql.jdbc.Driver
    #sh-cynosdbmysql-grp-cf0bewmq.sql.tencentcdb.com:21078
    druid:
      aop-patterns: com.atguigu.admin.*  #监控SpringBean
      filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）

      stat-view-servlet: # 配置监控页功能
        enabled: true
        login-username: admin
        login-password: admin
        resetEnable: false

      web-stat-filter: # 监控web
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'


      filter:
        stat: # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false
#
#mybatis:
#  mapper-locations: classpath*:mapper/*.xml
#  type-aliases-package: com.eiletxie.springcloud.entities
##    它一般对应我们的实体类所在的包，这个时候会自动取对应包中不包括包名的简单类名作为包括包名的别名。多个package之间可以用逗号或者分号等来进行分隔（value的值一定要是包的全）

# 配置mybatis规则
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  type-aliases-package: com.cloud.demo.entities

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
#      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2


debug: true
